#!/usr/bin/env bash

set -euo pipefail

# Force safe system fallback locales
export LANG=C.UTF-8
export LC_ALL=C.UTF-8

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"
# "remote" endpoint is configured in the rclone config file, and points to the remote drive where the docs are stored.
rclone sync docs remote:"HomeLab Operations/docs" >/dev/null 2>&1 &
