apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-infra-pod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-infra
  template:
    metadata:
      labels:
        app: test-infra
    spec:
      nodeSelector:
        node-role.kubernetes.io/infra: "true"
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-worker-pod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-worker
  template:
    metadata:
      labels:
        app: test-worker
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
      - name: web
        image: nginx:alpine
