apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-backend
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: "${KEY_VAULT_URI}"
      tenantId: "${TENANT_ID}"
      authSecretRef:
        clientId:
          name: azure-kv-credentials
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-kv-credentials
          key: ClientSecret
          namespace: external-secrets