apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: desec-token-sync
  namespace: cert-manager
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-backend # Matches the name from <kubectl get clustersecretstore output>
    kind: ClusterSecretStore
  target:
    name: desec-api-token-secret # The name of the native K8s secret it will create
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: desec-api-token # The exact name of the secret created in Azure Key Vault
