apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-private-repo-credentials
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore
  target:
    name: github-private-repo-ssh
    creationPolicy: Owner
    template:
      metadata:
        labels:
          # This label tells Argo CD to auto-discover this secret as repository credentials
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: "REPO_URL"
        sshPrivateKey: "{{ .ssh_key | toString }}"
  data:
    - secretKey: ssh_key
      remoteRef:
        key: argocd-repo-ssh-key
