apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-backup-credentials-sync
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-backup-credentials # The secret name the CronJob expects
    creationPolicy: Owner
  data:
  - secretKey: BW_CLIENTID
    remoteRef:
      key: vw-backup-client-id     # The name in Azure Key Vault
  - secretKey: BW_CLIENTSECRET
    remoteRef:
      key: vw-backup-client-secret # The name in Azure Key Vault
  - secretKey: VAULT_PASSWORD
    remoteRef:
      key: vw-backup-svc-password  # The Vaultwarden backup service user password in Azure Key Vault
  - secretKey: KDBX_PASSWORD
    remoteRef:
      key: vw-kdbx-password        # The KeePass archive encryption password in Azure Key Vault
  - secretKey: VW_REMOTE_API_TOKEN
    remoteRef:
      key: vw-backup-remote-api-token     # The remote API token in Azure Key Vault
